/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as PickingRouteImport } from './routes/picking'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as MisBenchmarksRouteImport } from './routes/mis-benchmarks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as InDeliveryRouteImport } from './routes/in-delivery'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DeliveredRouteImport } from './routes/delivered'
import { Route as CustomerCareRouteImport } from './routes/customer-care'
import { Route as CalendarsRouteImport } from './routes/calendars'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders_.$orderId'

const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const PickingRoute = PickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const MisBenchmarksRoute = MisBenchmarksRouteImport.update({
  id: '/mis-benchmarks',
  path: '/mis-benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const InDeliveryRoute = InDeliveryRouteImport.update({
  id: '/in-delivery',
  path: '/in-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveredRoute = DeliveredRouteImport.update({
  id: '/delivered',
  path: '/delivered',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCareRoute = CustomerCareRouteImport.update({
  id: '/customer-care',
  path: '/customer-care',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsRoute = CalendarsRouteImport.update({
  id: '/calendars',
  path: '/calendars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendars': typeof CalendarsRoute
  '/customer-care': typeof CustomerCareRoute
  '/delivered': typeof DeliveredRoute
  '/driver': typeof DriverRoute
  '/flags': typeof FlagsRoute
  '/in-delivery': typeof InDeliveryRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/mis-benchmarks': typeof MisBenchmarksRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/ready': typeof ReadyRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendars': typeof CalendarsRoute
  '/customer-care': typeof CustomerCareRoute
  '/delivered': typeof DeliveredRoute
  '/driver': typeof DriverRoute
  '/flags': typeof FlagsRoute
  '/in-delivery': typeof InDeliveryRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/mis-benchmarks': typeof MisBenchmarksRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/ready': typeof ReadyRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendars': typeof CalendarsRoute
  '/customer-care': typeof CustomerCareRoute
  '/delivered': typeof DeliveredRoute
  '/driver': typeof DriverRoute
  '/flags': typeof FlagsRoute
  '/in-delivery': typeof InDeliveryRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/mis-benchmarks': typeof MisBenchmarksRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/ready': typeof ReadyRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/warehouses': typeof WarehousesRoute
  '/orders_/$orderId': typeof OrdersOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendars'
    | '/customer-care'
    | '/delivered'
    | '/driver'
    | '/flags'
    | '/in-delivery'
    | '/locations'
    | '/login'
    | '/mis-benchmarks'
    | '/packing'
    | '/picking'
    | '/ready'
    | '/reports'
    | '/returns'
    | '/scheduled'
    | '/settings'
    | '/users'
    | '/warehouses'
    | '/orders/$orderId'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendars'
    | '/customer-care'
    | '/delivered'
    | '/driver'
    | '/flags'
    | '/in-delivery'
    | '/locations'
    | '/login'
    | '/mis-benchmarks'
    | '/packing'
    | '/picking'
    | '/ready'
    | '/reports'
    | '/returns'
    | '/scheduled'
    | '/settings'
    | '/users'
    | '/warehouses'
    | '/orders/$orderId'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/calendars'
    | '/customer-care'
    | '/delivered'
    | '/driver'
    | '/flags'
    | '/in-delivery'
    | '/locations'
    | '/login'
    | '/mis-benchmarks'
    | '/packing'
    | '/picking'
    | '/ready'
    | '/reports'
    | '/returns'
    | '/scheduled'
    | '/settings'
    | '/users'
    | '/warehouses'
    | '/orders_/$orderId'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarsRoute: typeof CalendarsRoute
  CustomerCareRoute: typeof CustomerCareRoute
  DeliveredRoute: typeof DeliveredRoute
  DriverRoute: typeof DriverRoute
  FlagsRoute: typeof FlagsRoute
  InDeliveryRoute: typeof InDeliveryRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  MisBenchmarksRoute: typeof MisBenchmarksRoute
  PackingRoute: typeof PackingRoute
  PickingRoute: typeof PickingRoute
  ReadyRoute: typeof ReadyRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  ScheduledRoute: typeof ScheduledRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WarehousesRoute: typeof WarehousesRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picking': {
      id: '/picking'
      path: '/picking'
      fullPath: '/picking'
      preLoaderRoute: typeof PickingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-benchmarks': {
      id: '/mis-benchmarks'
      path: '/mis-benchmarks'
      fullPath: '/mis-benchmarks'
      preLoaderRoute: typeof MisBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-delivery': {
      id: '/in-delivery'
      path: '/in-delivery'
      fullPath: '/in-delivery'
      preLoaderRoute: typeof InDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivered': {
      id: '/delivered'
      path: '/delivered'
      fullPath: '/delivered'
      preLoaderRoute: typeof DeliveredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-care': {
      id: '/customer-care'
      path: '/customer-care'
      fullPath: '/customer-care'
      preLoaderRoute: typeof CustomerCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars': {
      id: '/calendars'
      path: '/calendars'
      fullPath: '/calendars'
      preLoaderRoute: typeof CalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders_/$orderId': {
      id: '/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarsRoute: CalendarsRoute,
  CustomerCareRoute: CustomerCareRoute,
  DeliveredRoute: DeliveredRoute,
  DriverRoute: DriverRoute,
  FlagsRoute: FlagsRoute,
  InDeliveryRoute: InDeliveryRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  MisBenchmarksRoute: MisBenchmarksRoute,
  PackingRoute: PackingRoute,
  PickingRoute: PickingRoute,
  ReadyRoute: ReadyRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  ScheduledRoute: ScheduledRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WarehousesRoute: WarehousesRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
